version: "3"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    #   - "443:443"
    #   # - "3000:443"
    # expose:
    #   - "80"
    restart: always
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./https:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    
  client:
    depends_on:
      - nginx
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    container_name: client
    # ports:
    #   - "5173:5173"
    expose:
      - "5173"
    volumes:
      - ./https:/usr/share/nginx/html

  game:
    depends_on:
      - nginx
    build:
      context: ./game-server
      dockerfile: Dockerfile
    restart: always
    container_name: game-server
    # ports:
    #   - "8080:8080"
    expose:
      - "8080"
    volumes:
      - ./https:/usr/share/nginx/html
      - ./game-server:/app/

  socket:
    depends_on:
      - nginx
    build:
      context: ./socket-server
      dockerfile: Dockerfile
    restart: always
    container_name: socket-server
    # ports:
    #   - "3000:3000"
    expose:
      - "3001"
    volumes:
      - ./https:/usr/share/nginx/html
      - ./socket-server:/app/
  api:
    depends_on:
      - nginx
    build:
      context: ./api-server
      dockerfile: Dockerfile
    restart: always
    container_name: api-server
    # ports:
    #   - "5005:5005"
    expose:
      - "5005"
    volumes:
      - ./https:/usr/share/nginx/html
      - ./socket-server:/app/
  # certbot:
  #   # depends_on:
  #   #   - nginx
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #     - ./https:/usr/share/nginx/html
  #   command: certonly --webroot --webroot-path=/usr/share/nginx/html --email atthenoon@gmail.com --agree-tos --no-eff-email --keep-until-expiring -d para-solo.site -d www.para-solo.site
  #   # entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
